[profile.default]
src = "contracts/current"
out = "artifacts"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
build_info = true
build_info_path = "artifacts/build-info"
extra_output = ["metadata"]
remappings = [
    "@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

